### ISSUE TITLE
Haar Cascade to extract face rect

### ISSUE THREAD

**Issue by cjlcarvalho** [cjlcarvalho/how-are-you#2]
Please classify only the face rect, instead of the full image.

**Comment by anandhupvr** [comment]
@cjlcarvalho Is that you need print  HAPPY instaed of this cv2.imshow('How are you?', frame)

**Comment by cjlcarvalho** [comment]
@anandhupvr No, this issue is about training the ANN with only the face rect.

**Comment by bilalvur** [comment]
Do you want to edit [train.py of ann](https://github.com/cjlcarvalho/how-are-you/blob/master/ann/train.py)?
Do you want images to be preprocessed like following?
images -> HAAR -> processed images

Also can we assume that there is only 1 face in each image and faces are taken from frontal view?

**Comment by cjlcarvalho** [comment]
@bilalvur I think you don't need to add all the faces inside the result list in X method.

You can add only the main face, that will be the one with the largest area.

**Comment by bilalvur** [comment]
@cjlcarvalho i think i did the change that you wanted (in a little messy way). I also did small changes and added error checkings.

**Comment by cjlcarvalho** [comment]
@bilalvur Great! PR merged. :)

**Comment by cjlcarvalho** [comment]
@bilalvur I noticed another little thing that you can contribute with...

The test.py file also needs to extract faces, you can submit another PR fixing it.

I've created an issue about it: #4
